onesoft-sudo/sudobot

.eslintignore
.eslintrc
.github/workflows/build.yml
package.json
yarn.lock

Added ESLint

---

src/commands/moderation/BanCommand.ts
src/commands/moderation/ClearCommand.ts
src/commands/moderation/KickCommand.ts
src/commands/moderation/MassBanCommand.ts
src/commands/moderation/MuteCommand.ts
src/commands/moderation/SoftBanCommand.ts
src/commands/moderation/TempBanCommand.ts
src/utils/util.ts

Added non moderable role support so that users can not moderate other users having a specific role.
- Is Bugfix? Yes
- Relates issues: #33 
- Closes: #33

Add Non-moderable role

---

src/commands/moderation/BanCommand.ts
src/commands/moderation/ClearCommand.ts
src/commands/moderation/MassBanCommand.ts
src/commands/moderation/SoftBanCommand.ts
src/commands/moderation/TempBanCommand.ts
src/utils/getMember.ts
src/utils/getUser.ts

Fix wrong mention reading strategy.

fix: mention reading strategy

---

resources/welcome_messages.json
src/client/Client.ts
src/events/guildMember/GuildMemberAddEvent.ts
src/services/Welcomer.ts

Added random welcome messages support.
- Related issues: #21 
- Closes: #21

feat: random welcome messages

---

src/commands/moderation/ClearCommand.ts
src/commands/moderation/EchoCommand.ts
src/commands/moderation/KickCommand.ts
src/commands/moderation/LockCommand.ts
src/commands/moderation/MassBanCommand.ts
src/commands/moderation/MuteCommand.ts
src/commands/moderation/SetChPermsCommand.ts
src/commands/moderation/SoftBanCommand.ts
src/commands/moderation/TempBanCommand.ts
src/commands/moderation/UnbanCommand.ts
src/commands/moderation/UnmuteCommand.ts

- Related issues: #37 #39 
- Closes: #37 #39

refactor: permission based command protection

---

ecosystem.config.js
package.json

A short brief about your changes.
- Related issues: #53
- Closes: #53

chore: integrate with PM2 process manager (#53)

---

src/services/AFKEngine.ts

- Related issues: #84
- Closes: #84

fix: afk systems not working

---

src/utils/Pagination.ts

Added a re-usable paginator class for paginating data.

feat: add paginator class

---

src/commands/moderation/WarnCommand.ts

- Related issues: #91 
- Closes: #91

fix: warning command permissions

---

src/commands/information/ProfileCommand.ts

- Related issues: #86 
- Closes: #86

feat: make the spotify status song name clickable

---

src/commands/moderation/WarnCommand.ts
src/commands/settings/AboutCommand.ts

Updated embed by adding timestamp so the moderators know when the user has been warned and changed the embed color to red.

Warn command

---

README.md

Added "Extra" with dashboard link.

---

docs/legal/privacy.md

Updated the methods to contact.

---

src/automod/ProfileFilter.ts

- Related issues: #101
- Closes: #101

fix: do not unmute user if not muted 

---

src/automod/ProfileFilter.ts

If a user gets muted my profile filter and then someone mutes them manually again and the user changes their nickname to an appropriate one, then profile filter will unmute the user.
This issue has been fixed.
- Related issues: #106
- Closes: #106

fix(automod): profile filter interfering with manual mutes

---

src/utils/Pagination.ts

fix(pagination): update button emoji orders

---

src/commands/moderation/ShotCommand.ts

- Related issues: #113 
- Closes: #113

perf(shots): fix performance issues of shot command

---

src/commands/information/ProfileCommand.ts

- Related issues: #117 
- Closes: #117

feat(profile): show permission percentage

---

src/automod/SpamFilter.ts

Users can now add custom spam warning message in the config.

feat(spam_filter): custom spam warning message

---

src/services/Auth.ts

fix(auth): bot owner(s) can run any command

---

src/client/Client.ts
src/events/debug/DebugEvent.ts
src/services/DebugLogger.ts

* Use `DebugLogger` service as the central log manager.
* Remove unneeded comments from `Client`.
* Change `LogLevel` enum member values to uppercase words.
* Other minor improvements and fixes.

feat(debug-logging): better logging

---

src/automod/AutoResponder.ts
src/automod/Common.ts
src/automod/MessageFilter.ts
src/client/Client.ts
src/events/message/MessageCreateEvent.ts
src/events/message/MessageUpdateEvent.ts

* Respond when a specific word/token is found on the message content
* Works even after message edits

feat(automod): add autoresponder

---

deploy-commands.js
src/commands/moderation/SaveMessageCommand.ts

feat(commands): add message saving command

---

src/automod/AutoClear.ts
src/automod/Automute.ts
src/automod/Logger.ts
src/automod/OldLogger.ts
src/client/MessageEmbed.ts
src/commands/moderation/BanCommand.ts
src/commands/moderation/MuteCommand.ts
src/commands/moderation/ShotCommand.ts
src/commands/moderation/SoftBanCommand.ts
src/commands/moderation/TempBanCommand.ts
src/commands/moderation/UnbanCommand.ts
src/commands/moderation/UnmuteCommand.ts
src/commands/moderation/WarnCommand.ts
src/events/guildBan/GuildBanAddEvent.ts
src/events/guildBan/GuildBanRemoveEvent.ts
src/events/guildMember/GuildMemberAddEvent.ts
src/events/guildMember/GuildMemberRemoveEvent.ts
src/events/message/MessageDeleteEvent.ts
src/events/message/MessageUpdateEvent.ts
src/queues/UnbanQueue.ts

refactor(logger): update logger strategy and code quality

---

resources/welcome_messages.json

feat(welcomer): added a new welcome message

---

README.md

docs(readme): update mongodb atlas link text

---

src/automod/MessageRuleService.ts
src/types/MessageRuleSchema.ts

Changed the blockDomain rule to domain rule, which allows for an `allow` or `disallow` mode.

feat(message_rules): changed blockDomain rule into domain rule

---

config/schema/config.json
config/schema/system.json
src/automod/MessageFilter.ts
src/commands/settings/BlockedMessageCommand.ts
src/commands/settings/BlockedTokenCommand.ts
src/commands/settings/BlockedWordCommand.ts
src/services/LoggerService.ts
src/types/GuildConfigSchema.ts

Along with tokens and words, you can now block entire messages as well.

feat: added blocked messages to message filters

---

src/core/Client.ts
src/core/Event.ts
src/events/ReadyEvent.ts
src/events/channel/ChannelCreateEvent.ts
src/events/channel/ChannelDeleteEvent.ts
src/events/channel/ChannelUpdateEvent.ts
src/events/guildBan/GuildBanAddEvent.ts
src/events/guildBan/GuildBanRemoveEvent.ts
src/events/guildMember/GuildMemberAddEvent.ts
src/events/guildMember/GuildMemberRemoveEvent.ts
src/events/guildMember/GuildMemberUpdateEvent.ts
src/events/interaction/InteractionCreateEvent.ts
src/events/message/MessageCreateEvent.ts
src/events/message/MessageDeleteBulkEvent.ts
src/events/message/MessageDeleteEvent.ts
src/events/message/MessageUpdateEvent.ts
src/events/role/RoleCreateEvent.ts
src/events/role/RoleDeleteEvent.ts
src/events/role/RoleUpdateEvent.ts
src/services/ExtensionService.ts
src/types/GuildConfigSchema.ts

feat(extensions): better event handling

---

src/core/Client.ts
src/queues/BumpReminderQueue.ts
src/services/BumpReminderService.ts
src/types/GuildConfigSchema.ts

feat: bump reminder

---

config/schema/config.json
config/schema/system.json
src/services/WelcomerService.ts
src/types/GuildConfigSchema.ts

- New feature? *Yes*
- Closes: #142

feat: welcomer custom user greetings

---

docs/app/(docs)/commands/afk/page.mdx
docs/app/(docs)/commands/automation/afk/page.mdx
docs/app/(docs)/commands/ballot/page.mdx
docs/app/(docs)/commands/createreactionrole/page.mdx
docs/app/(docs)/commands/gafk/page.mdx

Added the following to the commands part of docs:
- afk
-  gafk
- ballot
- createreactionrole

Docs update

---

docs/app/(docs)/getting-started/page.mdx

I also noticed that the Getting Started page should receive a little update so that they are on 8.x, that way they have the latest updates.

Update the "Getting Started" page

---

docs/app/(docs)/getting-started/page.mdx

Deleted the "Your Discord server should have at least 50 members to be eligible." text due to the requirements being removed.

Update Getting Started page

---

docs/app/(docs)/faq/page.mdx
docs/app/page.mdx

I changed around the main page so that it says if you wish to add sudobot to your server, you need to read the tos, then if they accept it they can join the OSN server or dm rakin, then I added an entry to the FAQ stating how they can add the official sudobot to their server.

Update the main page and FAQ

---

docs/app/(docs)/getting-started/page.mdx

WHY WAS THIS SO STRESSFUL ON ME 😭
yeah title says it all, if i made a mistake let me know so i can fix it

add bun docs to get started

---

docs/app/(docs)/getting-started-v8/page.mdx

idk if this is gonna work or not so @virtual-designer i wanna know if it will or not

docs update ig?

---

.github/labeler.yml
src/main/typescript/automod/AIAutoModeration.ts
src/main/typescript/core/DiscordKernel.ts
src/main/typescript/events/message/MessageCreateEventListener.ts
src/main/typescript/events/message/MessageUpdateEventListener.ts
src/main/typescript/schemas/GuildConfigSchema.ts
src/main/typescript/schemas/ModerationActionSchema.ts
src/main/typescript/services/ModerationActionService.ts

AI accelerated auto moderation system that observes user behavior and takes action based on those information.

feat(automod): AI based auto moderation

---

docs/app/(docs)/getting-started/page.mdx

Currently, it doesn't sound correct. This is a mini PR to make it sound correct.

fix: make it sound correct

---

src/main/typescript/commands/system/BroadcastCommand.ts

A command that allows the system administrators to broadcast messages globally. It can be used to announce something, or notify all servers about something important.

feat: broadcast command

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
docs/app/(docs)/configuration/guild-config-schema/page.mdx

Updated GitHub links to reflect new location of `GuildConfigSchema.ts` and `SystemConfigSchema.ts`
- Is Bugfix? No

Configuration Page - Documentation Update
